# Generated by Django 5.2.6 on 2025-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, choices=[('perder_peso', 'Perder peso'), ('ganar_musculo', 'Ganar músculo'), ('tonificar', 'Tonificar'), ('mantener_forma', 'Mantenerme en forma')], max_length=50, null=True)),
                ('experience', models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50, null=True)),
                ('equipment', models.CharField(blank=True, choices=[('mancuernas', 'Mancuernas'), ('cuerpo', 'Sólo mi cuerpo'), ('bandas', 'Bandas de resistencia'), ('gimnasio', 'Máquinas de gimnasio')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Para evitar conflictos con el modelo de Django', related_name='custom_users_groups', related_query_name='user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Para evitar conflictos con el modelo de Django', related_name='custom_users_permissions', related_query_name='user', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
